data_paths:
  #- input/kaggle-llm-science-exam/train.csv
  #- input/additional-train-data-for-llm-science-exam/6000_train_examples.csv
  #- input/additional-train-data-for-llm-science-exam/extra_train_set.csv
  - input/15k-high-quality-examples/15k_gpt3.5-turbo.csv
  - input/15k-high-quality-examples/5900_examples.csv
  - input/llm-science-3k-data/test.csv
  - input/wikipedia-stem-1k/stem_1k_v1.csv
  - input/sci-or-not-sci-hypthesis-testing-pack/6000_all_categories_questions.csv
  - input/sci-or-not-sci-hypthesis-testing-pack/6000_wiki_en_sci_questions.csv

wiki_dir: input/wikipedia-20230701
wiki_index_path: input/wikipedia-20230701/wiki_2023_index.parquet
index_path: input/wikipedia-2023-07-faiss-index/wikipedia_202307.index
sim_model: all-MiniLM-L6-v2
max_length: 384
batch_size: 16
doc_top_k: 3
num_sentences_include: 5

debug: ${debug}
seed: 7