wiki_dir: input/llm-science-wikipedia-data-a
sim_model: thenlper/gte-small #BAAI/bge-small-en # all-MiniLM-L6-v2
max_sentence_length: 250
max_sentence_num: 300
max_length: 384
batch_size: 32

debug: ${debug}
seed: 7