data_paths:
  - input/kaggle-llm-science-exam/train.csv
  - preprocessed/901_concat/data2.csv
  - preprocessed/901_concat/data1.csv 
  
filter_wiki_path: preprocessed/400_base_data/filter_2_1.parquet
index_path: preprocessed/410_embedding_index/001/ivfpq_index.faiss
sim_model: intfloat/multilingual-e5-small

top_k: 10
max_length: 512
batch_size: 8

debug: ${debug}
seed: 7