data_paths:
  - preprocessed/901_concat/data1.csv
  - preprocessed/901_concat/data2.csv
  - preprocessed/901_concat/data0_0.csv
  - preprocessed/901_concat/data0_10000.csv
  - preprocessed/901_concat/data0_20000.csv
  - preprocessed/901_concat/data0_30000.csv
  - preprocessed/901_concat/data0_40000.csv
  - preprocessed/901_concat/data0_50000.csv
  - preprocessed/901_concat/data0_60000.csv
  - preprocessed/901_concat/data0_70000.csv
  - preprocessed/901_concat/data0_80000.csv
  - preprocessed/901_concat/data0_90000.csv

wiki_dir: input/llm-science-wikipedia-data # オリジナル抽出データ
wiki_index_path: preprocessed/220_doc_index/000/all.parquet
index_path: preprocessed/220_doc_index/000/ivfpq_index.faiss
sim_model: BAAI/bge-small-en
max_length: 384
batch_size: 32
doc_top_k: 10
num_sentences_include: 15
window_size: 4
sliding_size: 3

debug: ${debug}
seed: 7