data_paths:
  - preprocessed/901_concat/data2.csv
  - preprocessed/901_concat/data0.csv
  - preprocessed/901_concat/data1.csv

wiki_dir: input/llm-science-wikipedia-data # オリジナル抽出データ
wiki_index_path: preprocessed/220_doc_index/000/all.parquet
index_path: preprocessed/220_doc_index/000/ivfpq_index.faiss
sim_model: BAAI/bge-small-en
max_length: 384
batch_size: 8
doc_top_k: 10
num_sentences_include: 20

debug: ${debug}
seed: 7