data_paths:
  - preprocessed/901_concat/data0.csv
  - preprocessed/901_concat/data1.csv
  - preprocessed/901_concat/data2.csv

wiki_dir: input/llm-science-wikipedia-data-b 
wiki_index_path: preprocessed/320_doc_index/001/all.parquet # b
index_path: preprocessed/320_doc_index/001/ivfpq_index.faiss
sim_model: BAAI/bge-small-en
max_length: 384
batch_size: 8
doc_top_k: 10
num_sentences_include: 15
window_size: 3
sliding_size: 2

debug: ${debug}
seed: 7