data_paths:
  - input/validation-500/val_500_enhanced.csv
  - input/kaggle-llm-science-exam/train.csv
  #- preprocessed/901_concat/data1.csv
  #- preprocessed/901_concat/data2.csv
  
wiki_dir: input/llm-science-wikipedia-data-b 
wiki_index_path: preprocessed/320_doc_index/004/all.parquet # b
index_path: preprocessed/320_doc_index/004/ivfpq_index.faiss
sim_model: BAAI/bge-base-en-v1.5
max_length: 512
batch_size: 8
num_sentences_include: 20
doc_top_k: 10
window_size: 5
sliding_size: 4

debug: ${debug}
seed: 7