data_paths:
  - input/kaggle-llm-science-exam/train.csv
  - preprocessed/902/data2.csv
  - preprocessed/902/data1.csv 
  - preprocessed/902/data0_0.csv
  - preprocessed/902/data0_10000.csv
  - preprocessed/902/data0_20000.csv
  - preprocessed/902/data0_30000.csv
  - preprocessed/902/data0_40000.csv
  - preprocessed/902/data0_50000.csv
  - preprocessed/902/data0_60000.csv
  - preprocessed/902/data0_70000.csv
  - preprocessed/902/data0_80000.csv
  - preprocessed/902/data0_90000.csv
  - preprocessed/902/data0_100000.csv
  
wiki_dir: input/llm-science-wikipedia-data-b 
wiki_index_path: preprocessed/320_doc_index/001/all.parquet # b
index_path: preprocessed/320_doc_index/001/ivfpq_index.faiss
sim_model: BAAI/bge-small-en
max_length: 384
batch_size: 32
num_sentences_include: 20
doc_top_k: 10
window_size: 4
sliding_size: 3

debug: ${debug}
seed: 7