data_paths:
  - input/kaggle-llm-science-exam/train.csv
  - preprocessed/901_concat/data2.csv
  - preprocessed/901_concat/data1.csv 
  
filter_wiki_path: preprocessed/500_index/stem-wiki-cohere-no-emb.parquet
index_path: preprocessed/500_index/nparse_multi_large/index.faiss
sim_model: intfloat/multilingual-e5-large

top_k: 10
max_length: 512
batch_size: 8

debug: ${debug}
seed: 7
