data_paths:
  - input/validation-500/val_500_enhanced.csv
  # - input/kaggle-llm-science-exam/train.csv
  #- preprocessed/901_concat/data1.csv
  #- preprocessed/901_concat/data2.csv
  
filter_wiki_path: preprocessed/500_index/stem-wiki-cohere-no-emb.parquet
index_path: preprocessed/500_index/nparse_bge_base/index.faiss
sim_model: BAAI/bge-base-en-v1.5

top_k: 10
max_length: 512
batch_size: 8

debug: ${debug}
seed: 7
