data_paths:
  - input/validation-500/val_500_enhanced.csv
  - input/kaggle-llm-science-exam/train.csv
  #- preprocessed/901_concat/data1.csv
  #- preprocessed/901_concat/data2.csv
  
wiki_dir: input/llm-science-wikipedia-data-b 
wiki_index_path: preprocessed/320_doc_index/003/all.parquet # b
index_path: preprocessed/320_doc_index/003/ivfpq_index.faiss
sim_model: sentence-transformers/all-MiniLM-L12-v2
max_length: 512
batch_size: 16
num_sentences_include: 20
doc_top_k: 10
window_size: 4
sliding_size: 3

debug: ${debug}
seed: 7